spring:
  application:
    name: external-movie-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-documentation

movie:
  service:
    url: lb://data-movie-service
